-- MySQL Script generated by MySQL Workbench
-- Thu Feb 16 17:46:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Migraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Migraciones` (
  `Year` INT NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Emigrants` INT NOT NULL,
  `Population` INT NOT NULL,
  `Relative_migration` DECIMAL(3) NOT NULL,
  `Migracionescol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Country`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pib`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pib` (
  `Year` INT NOT NULL,
  `PIB` DECIMAL(3) NOT NULL,
  `Migraciones_Country` VARCHAR(45) NOT NULL,
  INDEX `fk_Pib_Migraciones_idx` (`Migraciones_Country` ASC) VISIBLE,
  CONSTRAINT `fk_Pib_Migraciones`
    FOREIGN KEY (`Migraciones_Country`)
    REFERENCES `mydb`.`Migraciones` (`Country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ocupacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ocupacion` (
  `Year` INT NOT NULL,
  `Tasa_ocupacion` DECIMAL(5) NOT NULL,
  `valor_obs` DECIMAL(3) NULL,
  `sexo` VARCHAR(10) NULL,
  `Migraciones_Country` VARCHAR(45) NOT NULL,
  INDEX `fk_Ocupacion_Migraciones1_idx` (`Migraciones_Country` ASC) VISIBLE,
  CONSTRAINT `fk_Ocupacion_Migraciones1`
    FOREIGN KEY (`Migraciones_Country`)
    REFERENCES `mydb`.`Migraciones` (`Country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salario` (
  `Salario_real` DECIMAL(3) NOT NULL,
  `inflacion` DECIMAL(3) NOT NULL,
  `Salario_nom` DECIMAL(3) NOT NULL,
  `Migraciones_Country` VARCHAR(45) NOT NULL,
  INDEX `fk_Salario_Migraciones1_idx` (`Migraciones_Country` ASC) VISIBLE,
  CONSTRAINT `fk_Salario_Migraciones1`
    FOREIGN KEY (`Migraciones_Country`)
    REFERENCES `mydb`.`Migraciones` (`Country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
